routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/emulate', function(){
    for($a=0; $a<30; $a++){

        $players = \App\Services\Facades\MatchPlayer::startMatchAndGetPlayersKeys();
        $player1 = $players[0];
        dump($player1);
        $player2 = $players[1];
        dump($player2);

        \App\Services\Facades\MatchPlayer::lost($player1);
        \App\Services\Facades\MatchPlayer::won($player2);
    }
});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/play', 'PlayGameController@play');

Route::post('/endgame', 'PlayGameController@endgame')->name('endgame');

Route::get('/score', 'PlayGameController@score');

Route::get('/champions', 'PlayGameController@champions')->name('champions');

Route::group(['middleware'=>'admin', 'prefix'=>'admin'], function() {

    Route::get('/championship', 'SetGameController@startChampionship');
    Route::post('/generate-championship', 'SetGameController@generateChampionship')->name('generate');

    Route::resource('/apis', 'ApiController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('/fetchers', 'FetcherController', ['except'=>['edit','update']]);
});

resources/views/admin/modals/create-api.blade.php
<!-- The Modal -->
<div class="modal fade" id="newApi">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Modal Heading</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="POST" action="{{route('apis.store')}}">
                    {{csrf_field()}}
                    <div class="form-group">
                        <label for="base_uri">Base Uri:</label>
                        <input type="url" class="form-control" id="base_uri" placeholder="Base Uri" name="base_uri">
                    </div>
                    <div class="form-group">
                        <label for="request_limit">Requests Limit:</label>
                        <input type="number" min="1" max="200" class="form-control" id="request_limit" placeholder="Request Limit" name="request_limit" required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

resources/views/admin/modals/edit-api.blade.php
<!-- The Modal -->
<div class="modal fade" id="Api{{$api->id}}">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Modal Heading</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="POST" action="{{route('apis.update', ['id'=>$api->id])}}">
                    {{ csrf_field() }}
                    @method('PATCH')
                    <input type="number" name="id" value="{{$api->id}}" hidden>
                    <div class="form-group">
                        <label for="base_uri">Base Uri:</label>
                        <input type="url" value="{{$api->base_uri}}" class="form-control" id="base_uri" placeholder="Base Uri" name="base_uri">
                    </div>
                    <div class="form-group">
                        <label for="request_limit">Requests Limit:</label>
                        <input type="number" value="{{$api->request_limit}}" min="1" max="200" class="form-control" id="request_limit" placeholder="Request Limit" name="request_limit" required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm">Update</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>