routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/emulate', function(){
    for($a=0; $a<30; $a++){

        $players = \App\Services\Facades\MatchPlayer::startMatchAndGetPlayersKeys();
        $player1 = $players[0];
        dump($player1);
        $player2 = $players[1];
        dump($player2);

        \App\Services\Facades\MatchPlayer::lost($player1);
        \App\Services\Facades\MatchPlayer::won($player2);
    }
});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/play', 'PlayGameController@play');

Route::post('/endgame', 'PlayGameController@endgame')->name('endgame');

Route::get('/score', 'PlayGameController@score');

Route::get('/champions', 'PlayGameController@champions')->name('champions');

Route::group(['middleware'=>'admin', 'prefix'=>'admin'], function() {

    Route::get('/championship', 'SetGameController@startChampionship');
    Route::post('/generate-championship', 'SetGameController@generateChampionship')->name('generate');

    Route::resource('/apis', 'ApiController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('/fetchers', 'FetcherController', ['except'=>['edit','update']]);
});

app/Fetcher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Fetcher extends Model
{
    #region CLASS PROPERTIES
    protected $table = 'fetchers';
    protected $fillable = [
        'api_id','fetcher_type_id', 'name','endpoint','request_limit','next_link',
        'all_results_field','all_results_subfield','field_1','field_2','field_3','field_4',
        'image_url','entity_url'
    ];
    #endregion

    #region MAIN METHODS
    #endregion

    #region SCOPE METHODS
    #endregion

    #region RELATION METHODS
    public function api()
    {
        return $this->belongsTo(Api::class);
    }

    public function fetcher_type()
    {
        return $this->belongsTo(FetcherType::class);
    }
    #endregion
}

app/FetcherType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FetcherType extends Model
{
    #region CLASS PROPERTIES
    protected $table = 'fetcher_types';
    protected $fillable = [

    ];
    #endregion

    #region MAIN METHODS
    #endregion

    #region SCOPE METHODS
    #endregion

    #region RELATION METHODS
    public function fetchers()
    {
        return $this->hasMany(Fetcher::class);
    }
    #endregion
}

app/Http/Controllers/FetcherController.php
<?php

namespace App\Http\Controllers;

use App\Api;
use App\Fetcher;
use App\FetcherType;
use App\Http\Requests\StoreFetcherPost;

class FetcherController extends Controller
{
    #region RESOURCE METHODS
    public function index()
    {
        $fetchers = Fetcher::orderBy('api_id')
            ->with(['api','fetcher_type'])
            ->get();

        return view('admin.fetchers.fetchers')->with([
            'fetchers'=>$fetchers
        ]);
    }

    public function destroy($id)
    {
        $fetcher = Fetcher::find($id);
        $fetcher->delete();
        echo "yes";
    }

    public function create()
    {
        $apis = Api::all();
        $fetcherTypes = FetcherType::all();
        return view('admin.fetchers.fetcher-create')->with([
            'apis'=>$apis,
            'fetcherTypes'=>$fetcherTypes
        ]);
    }


    public function store(StoreFetcherPost $request)
    {
        Fetcher::create($request->only([
            'api_id','fetcher_type_id', 'name','endpoint','request_limit','next_link',
            'all_results_field','all_results_subfield','field_1','field_2','field_3','field_4',
            'image_url','entity_url'
        ]));

        session()->flash('message','New Fetcher saved successfully to DB!');
        return redirect()->back();
    }

    public function show($id)
    {
        $fetcher = Fetcher::with(['api','fetcher_type'])->find($id);

        return view('admin.fetchers.fetcher-show')->with([
            'fetcher' => $fetcher
        ]);
    }
    #endregion

    #region MAIN METHODS

    #endregion
}

resources/views/admin/fetchers/fetcher-create.blade.php
@extends('admin.admin')

@section('body')
    <div class="card">
        <div class="card-header">Fetcher </div>
        <div class="card-body">
            @include('messages.messages')
            @include('messages.errors')
            <form method="POST" action="{{route('fetchers.store')}}">
                {{csrf_field()}}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <div class="form-group">
                            <label for="api_id">
                                Select base uri (select one):
                            </label>
                            <select class="form-control" id="api_id" name="api_id">
                                <option>Selection required!</option>
                                @foreach($apis AS $api)
                                    <option value="{{$api->id}}">{{$api->base_uri}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <div class="form-group">
                            <label for="fetcher_type_id">
                                Select fetcher class (select one):
                            </label>
                            <select class="form-control" id="fetcher_type_id" name="fetcher_type_id">
                                <option>Selection required!</option>
                                @foreach($fetcherTypes AS $fetcherType)
                                    <option value="{{$fetcherType->id}}">{{$fetcherType->fetcher_class}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" id="name" placeholder="Enter unique name" name="name" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="endpoint">Endpoint:</label>
                        <input type="text" class="form-control" id="endpoint" placeholder="Enter endpoint" name="endpoint" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="request_limit">Request Limit:</label>
                        <input type="number" min="1" max="100" class="form-control" id="request_limit" placeholder="Enter request limit" name="request_limit" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="next_link">Next Link:</label>
                        <input type="text" class="form-control" id="next_link" placeholder="Enter next link" name="next_link" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="all_results_field">All Results Field:</label>
                        <input type="text" class="form-control" id="all_results_field" placeholder="Enter All Results Field" name="all_results_field" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="all_results_subfield">All Results Subfield:</label>
                        <input type="text" class="form-control" id="all_results_subfield" placeholder="Enter All Results Subfield (two steps only)" name="all_results_subfield">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="field_1">Field 1:</label>
                        <input type="text" class="form-control" id="field_1" placeholder="Enter field_1 name" name="field_1" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="field_2">Field 2:</label>
                        <input type="text" class="form-control" id="field_2" placeholder="Enter field_2 name" name="field_2" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="field_3">Field 3:</label>
                        <input type="text" class="form-control" id="field_3" placeholder="Enter field_3 name" name="field_3" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="field_4">Field 4:</label>
                        <input type="text" class="form-control" id="field_4" placeholder="Enter field_4 name" name="field_4" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="image_url">Image Url:</label>
                        <input type="url" class="form-control" id="image_url" placeholder="Enter image url name" name="image_url">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="fentity_url">Entity Url:</label>
                        <input type="url" class="form-control" id="entity_url" placeholder="Enter entity url name (one step only)" name="entity_url">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/fetchers/fetcher-show.blade.php
@extends('admin.admin')

@section('body')
    <div class="card">
        <div class="card-header">Fetcher </div>
        <div class="card-body">
            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="api">Api:</label>
                        <input type="text" class="form-control" id="api" value="{{$fetcher->api->base_uri}}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="endpoint">Endpoint:</label>
                        <input type="text" class="form-control" id="endpoint" value="{{$fetcher->endpoint}}" readonly>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="api_request_limit">Api requests qty limit:</label>
                        <input type="text" class="form-control" id="api_request_limit" value="{{$fetcher->api->request_limit}}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="endpoint_request_limit">Endpoint requests qty limit:</label>
                        <input type="text" class="form-control" id="endpoint_request_limit" value="{{$fetcher->request_limit}}" readonly>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="fetcher_type_name">Fetcher Type Name:</label>
                        <input type="text" class="form-control" id="fetcher_type_name" value="{{$fetcher->fetcher_type->name}}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="fetcher_type_class_name">Fetcher Class Name:</label>
                        <input type="text" class="form-control" id="fetcher_type_class_name" value="{{$fetcher->fetcher_type->fetcher_class}}" readonly>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label for="fetcher_type_description">Fetcher Type Description:</label>
                        <textarea class="form-control" id="fetcher_type_description"readonly>{{$fetcher->fetcher_type->description}}</textarea>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="all_results_field">Results field (for one and two steps fetchers):</label>
                        <input type="text" class="form-control" id="all_results_field" value="{{$fetcher->all_results_field}}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="all_results_subfield">Results subfield (for two steps fetchers ONLY):</label>
                        <input type="text" class="form-control" id="all_results_subfield" value="{{$fetcher->all_results_subfield}}" readonly>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="field_1">Field 1:</label>
                        <input type="text" class="form-control" id="field_1" value="{{$fetcher->field_1}}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="field_2">Field 2:</label>
                        <input type="text" class="form-control" id="field_2" value="{{$fetcher->field_2}}" readonly>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="field_3">Field 3:</label>
                        <input type="text" class="form-control" id="field_3" value="{{$fetcher->field_3}}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="field_4">Field 4:</label>
                        <input type="text" class="form-control" id="field_4" value="{{$fetcher->field_4}}" readonly>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="image_url">Image Url:</label>
                        <input type="text" class="form-control" id="image_url" value="{{$fetcher->image_url}}" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="entity_url">Entity Url (for one step fetchers ONLY):</label>
                        <input type="text" class="form-control" id="entity_url" value="{{$fetcher->entity_url}}" readonly>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/fetchers/fetchers.blade.php
@extends('admin.admin')

@section('body')
    @if(count($fetchers)>0)
    <div class="card">
        <div class="card-header">Fetchers</div>
        <div class="card-body">
            <table class="table table-striped table-responsive" >
                <thead>
                <tr>
                    <th>Base Uri</th>
                    <th>Endpoint</th>
                    <th>Fetcher Name</th>
                    <th>Serving Class</th>
                    <th>Details</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach($fetchers AS $fetcher)
                    <tr>
                        <td>{{$fetcher->api->base_uri}}</td>
                        <td>{{$fetcher->endpoint}}</td>
                        <td>{{$fetcher->name}}</td>
                        <td>{{$fetcher->fetcher_type->fetcher_class}}</td>
                        <td>
                            <a href="/admin/fetchers/{{$fetcher->id}}" class="btn btn-info btn-sm" role="button">Details</a>
                        </td>
                        <td>
                            <a href="#"
                               class="btn btn-danger btn-sm del"
                               role="button"
                               id="{{route('fetchers.destroy',['id'=>$fetcher->id])}}">
                                Delete
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @endif
    <a href="{{route('fetchers.create')}}" class="btn btn-success btn-block btn-sm" role="button">Create New EndPoint</a>
    <script>
        $(document).ready(function(){
            $('.del').on('click', function(){
                var url = $(this).attr('id');
                $.post
                (
                    url,
                    {
                        "_token": "{{ csrf_token() }}",
                        "_method": "DELETE"
                    },
                    function(data)
                    {
                        if(data === 'yes'){
                            location.reload();
                        }
                    }
                );
            })
        });
    </script>
@endsection