routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/emulate', function(){
    for($a=0; $a<30; $a++){

        $players = \App\Services\Facades\MatchPlayer::startMatchAndGetPlayersKeys();
        $player1 = $players[0];
        dump($player1);
        $player2 = $players[1];
        dump($player2);

        \App\Services\Facades\MatchPlayer::lost($player1);
        \App\Services\Facades\MatchPlayer::won($player2);
    }
});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/play', 'PlayGameController@play');

Route::post('/endgame', 'PlayGameController@endgame')->name('endgame');

Route::get('/score', 'PlayGameController@score');

Route::get('/champions', 'PlayGameController@champions')->name('champions');

Route::group(['middleware'=>'admin', 'prefix'=>'admin'], function() {

    Route::get('/championship', 'SetGameController@startChampionship');
    Route::post('/generate-championship', 'SetGameController@generateChampionship')->name('generate');

    Route::resource('/apis', 'ApiController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('/fetchers', 'FetcherController', ['except'=>['edit','update']]);
});

app/Api.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Api extends Model
{
    #region CLASS PROPERTIES
    protected $table = 'apis';
    protected $fillable = ['base_uri','request_limit'];
    #endregion

    #region MAIN METHODS
    #endregion

    #region SCOPE METHODS
    #endregion

    #region RELATION METHODS
    public function fetchers()
    {
        return $this->hasMany(Fetcher::class);
    }
    #endregion
}

app/Http/Controllers/ApiController.php
<?php

namespace App\Http\Controllers;

use App\Api;
use App\Http\Requests\StoreApiPost;
use App\Http\Requests\UpdateApiPatch;

class ApiController extends Controller
{
    #region RESOURCE METHODS
    public function index()
    {
        $apis = Api::all();
        return view('admin.apis.apis')->with([
            'apis'=>$apis
        ]);
    }

    public function destroy($id)
    {
        $api = Api::find($id);
        $api->delete();
        echo "yes";
    }

    public function store(StoreApiPost $request)
    {
        Api::create($request->only(['base_uri','request_limit']));

        session()->flash('message','New API saved successfully to DB!');
        return redirect()->back();
    }

    public function update(UpdateApiPatch $request, $id)
    {
        $api = Api::find($id);
        $api->update($request->only(['base_uri','request_limit']));
        session()->flash('message','Existing API was successfully updated!');
        return redirect()->back();
    }
    #endregion
}

resources/views/admin/apis/apis.blade.php
@extends('admin.admin')

@section('body')
    <div class="card">
        <div class="card-header">Fetchers</div>
        @if(count($apis)>0)
        <div class="card-body">
            @include('messages.messages')
            @include('messages.errors')
            <table class="table table-striped table-responsive" >
                <thead>
                <tr>
                    <th>Base Uri</th>
                    <th>Request Limit</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($apis AS $api)
                        <tr>
                            <td>{{$api->base_uri}}</td>
                            <td>{{$api->request_limit}}</td>
                            <td>
                                <button type="button" class="btn btn-info btn-block btn-sm" data-toggle="modal" data-target="#Api{{$api->id}}">
                                    Edit Api
                                </button>
                                @include('admin.modals.edit-api')
                            </td>
                            <td>
                                <a href="#"
                                   class="btn btn-danger btn-sm del"
                                   role="button"
                                   id="{{route('apis.destroy',['id'=>$api->id])}}">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @endif
        <button type="button" class="btn btn-success btn-block btn-sm" data-toggle="modal" data-target="#newApi">
            Create New Api
        </button>
        @include('admin.modals.create-api')
    </div>
    <script>
        $(document).ready(function(){
            $('.del').on('click', function(){
                var url = $(this).attr('id');
                $.post
                (
                    url,
                    {
                        "_token": "{{ csrf_token() }}",
                        "_method": "DELETE"
                    },
                    function(data)
                    {
                        if(data === 'yes'){
                            location.reload();
                        }
                    }
                );
            })
        });
    </script>
@endsection